source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftPagedFlow_Example', :exclusive => true do
  pod "SwiftPagedFlow", :path => "../"
end

target 'SwiftPagedFlow_Tests', :exclusive => true do
  pod "SwiftPagedFlow", :path => "../"

  
end
